### ISSUE TITLE
请问一下,作者什么时候可以把地址联动加上?

### ISSUE THREAD

**Issue by smallke** [ustbhuangyi/picker#10]
请问一下,作者什么时候可以把地址联动加上?  RT,作者可以加入到后续开发计划当中...或者提供相应接口

**Comment by ustbhuangyi** [comment]
ok，我抽空写一个demo吧

**Comment by ustbhuangyi** [comment]
demo 里已经更新，有地址联动的例子，不过数据都是fake的，可以参考其中对 picker API 的使用
