### ISSUE TITLE
跑不起来啊

### ISSUE THREAD

**Issue by cqgsm** [ustbhuangyi/picker#14]

**Comment by ustbhuangyi** [comment]
参考 Readme 如何构建部分，确保 `npm install` 所有依赖已经正确安装。

**Comment by neurotoxinvx** [comment]
@cqgsm 你是不是npm3+呢 ？ 是的话请重新git clone一下项目，执行npm install试一下~

**Comment by cqgsm** [comment]
> picker@1.1.1 dev C:\Users\asus-pc\Desktop\11\picker
> webpack-dev-server --port 9090 --inline --hot --content-base ./demo --host 0.0.0.0

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:9090
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1227:14)
    at listen (net.js:1263:10)
    at net.js:1372:9
    at nextTickCallbackWith3Args (node.js:486:9)
    at process._tickCallback (node.js:392:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
    at node.js:1001:3

**Comment by neurotoxinvx** [comment]
@cqgsm 看起来是你的9090端口被占用了~修改一下package.json里的 "scripts"下"dev"，把9090改成其他端口即可

**Comment by cqgsm** [comment]
ERROR in Cannot find module 'eslint'
 @ multi picker
webpack: bundle is now VALID.
这个已经出现两次了，非常感谢@@neurotoxinvx 耐心回答，不胜感激

**Comment by neurotoxinvx** [comment]
@cqgsm npm install eslint 不客气~

**Comment by cqgsm** [comment]
@neurotoxinvx 跑起来了，能用啦，非常感谢啊，有没有不用webpack打包的源码啊？

**Comment by neurotoxinvx** [comment]
@cqgsm dist目录下的picker.min.js即是~
