### ISSUE TITLE
如果同一个页面中初始化了多个picker，会出现异常

### ISSUE THREAD

**Issue by zhaowangdaren** [ustbhuangyi/picker#17]
异常导致数据无法滚动，数字变形

**Comment by ustbhuangyi** [comment]
能不能有一个可以复现的地址，目前看到我们的 demo 就是用的多个 picker ，也并无问题喔~

**Comment by zhaowangdaren** [comment]
https://github.com/zhaowangdaren/untitled.git
index页面有一个input。在手机端，先点击两个picker->点击input->点击picker，这时就会出现picker不能滚动，或者样式异常

**Comment by neurotoxinvx** [comment]
需要使用2个不同的picker时请实例化2个picker～
例: 
var picker1 = new Picker(...)
var picker2 = new Picker(...)

picker1.on(....)
picker2.on(....)
