### ISSUE TITLE
构建时候报错

### ISSUE THREAD

**Issue by littlebaozi** [ustbhuangyi/picker#20]
ERROR in ./~/.0.23.1@css-loader!./~/.1.6.1@stylus-loader!./src/picker/picker.styl
Module build failed: TypeError: E:\Project\happyvalleyApp-pay\plugins\picker\src\picker\picker.styl:111:1
   107|   .border-1px
   108|     &::after, &::before
   109|       -webkit-transform: scaleY(.5)
   110|       transform: scaleY(.5)
   111|
--------^
   112|

Path must be a string. Received undefined

window 10/ node v6.9.1/ npm v3.10.5

**Comment by superchangme** [comment]
我也报错拟解决了吗

**Comment by neurotoxinvx** [comment]
或许是 Node 版本偏高导致，可以尝试降级到 4.x 再试一下 ~

**Comment by ustbhuangyi** [comment]
package.json 依赖已经修改，可以再尝试安装一下
