### ISSUE TITLE
警示：插件有致命bug,不要使用

### ISSUE THREAD

**Issue by yangerlang** [ustbhuangyi/picker#22]
当页面长度超过一屏，页面有滚动条时，当向下滑动滚动条，然后再点击插件选择，插件完全不能上下滑动进行选择，在苹果5，苹果6s下，chrome,safari,uc，安卓的 uc, 手机百度，浏览器测试都有这个问题。提醒大家，此bug不解决,不要使用此插件

**Comment by ustbhuangyi** [comment]
fixed
