### ISSUE TITLE
有谁提供个二次开发的DateTime呢？

### ISSUE THREAD

**Issue by cipchk** [ustbhuangyi/picker#29]
不然我自己撸了！

**Comment by ustbhuangyi** [comment]
参考 https://github.com/ustbhuangyi/time-picker

**Comment by cipchk** [comment]
DEMO中无法点确定？
另，picker应该是老版本的。

**Comment by ustbhuangyi** [comment]
确实是老的 picker，可以借鉴一下思路~ 可以把 timepicker 放到当前 picker 的 demo 里，欢迎给 picker 提供 pr~
