### ISSUE TITLE
在selectedIndex的问题后又发现了一个问题

### ISSUE THREAD

**Issue by xwpongithub** [ustbhuangyi/picker#34]
如果初始传入selectedIndex值，如[6,2,2],之后关闭picker，重新根据这个值打开，重新修改第二列的数据时发现第三列没有对应的数据显示了~这是不是又是个bug~

**Comment by ustbhuangyi** [comment]
这个是 picker 联动 demo 并没有考虑到这种情况，如果想解决的话需要修改的是 picker demo 的代码，这这个不是 picker 的bug，picker 提供的接口和事件是可以实现这个功能的。

**Comment by xwpongithub** [comment]
哦哦~谢谢黄老师~
