### ISSUE TITLE
android手机的webview不支持吗？

### ISSUE THREAD

**Issue by LeiWang12** [ustbhuangyi/picker#35]
在安卓手机webview上，选择‘’项目‘’后点击‘’确定’’按钮 不会触发 picker.select 或者 picker.change 或者 picker.valuechange方法

**Comment by neurotoxinvx** [comment]
请提供更多的描述信息 如手机型号/安卓系统版本/浏览器UA

**Comment by LeiWang12** [comment]
谢谢您的回复，不是手机上浏览器，是原生andriod开发内置webview 打开一个h5 页面


发自网易邮箱大师
在2017年02月28日 23:46，王宏宇 写道：

请提供更多的描述信息 如手机型号/安卓系统版本/浏览器UA

**Comment by neurotoxinvx** [comment]
android webview 同样可以获取到 UA 哦

**Comment by LeiWang12** [comment]
好了 谢谢


发自网易邮箱大师
在2017年03月01日 11:52，王宏宇 写道：

android webview 同样可以获取到 UA 哦
