### ISSUE TITLE
显示所有二级项目？

### ISSUE THREAD

**Issue by riskers** [ustbhuangyi/picker#5]
比如一个地区选择，应该是先选定是北京还是上海，然后再选择是哪个区，现在把所有二级项目都显示出来了，不合理啊

**Comment by ustbhuangyi** [comment]
这个可能需要你基于picker做一些二次开发，比如picker是可以知道每一列滚动停止的事件，也支持动态更新某一列的数据。
可以参考这个代码https://github.com/ustbhuangyi/time-picker 
picker的一种高级应用，列之间的数据是联动的。

**Comment by riskers** [comment]
谢谢，原来还有 refill 方法
