### ISSUE TITLE
有2列数据，可不可以实现第二列的数据随着第一列的数据变化而自动变化

### ISSUE THREAD

**Issue by zhaowangdaren** [ustbhuangyi/picker#7]
A、B两列，第一列变了，第二列的数据会有变动，这个能实现吗？

**Comment by ustbhuangyi** [comment]
可以实现，当一列滚动停止的时候，会派发 picker.change 事件，同时会传递列序号 index 及滚动停止的位置 selectedIndex。你需要监听 picker.change 事件，在这个事件的回调函数中再调用refill(data, index)的方法，重填某一列的数据，data为数据数组，index为列序号。

**Comment by yangerlang** [comment]
如果picker.change后获取数据是异步的，接口比较慢，这个时候点击确定会导致取不到值的问题，有没有办法这个歌时候设置确定按钮不可以点？？
