### ISSUE TITLE
viewport自动缩放好改吗

### ISSUE THREAD

**Issue by anUglyDog** [ustbhuangyi/picker#8]
信了淘宝的忽悠,viewport自动缩放了,不是大多数那种设置为1.0了..
现在搜索到的picker都是1.0倍的,并且我找到的你的picker是最流畅的(同样流畅度的picker不超过两个)..
好不好改.

**Comment by ustbhuangyi** [comment]
淘宝的lib-flexible？那个方案都是2年前的做法了，现在flex的支持度已经非常好了，建议用flex实现移动端的弹性布局吧，viewport标准的设置即可： <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">

**Comment by anUglyDog** [comment]
现在淘宝首页还是自动缩放的啊

**Comment by ustbhuangyi** [comment]
移动端一般是不建议缩放的，建议去看一下手淘的源码，viewport设置和我说的一样

**Comment by anUglyDog** [comment]
你在哪看的..
`<meta name="viewport" content="initial-scale=0.3333333333333333, maximum-scale=0.3333333333333333, minimum-scale=0.3333333333333333, user-scalable=no">`
我打开是缩放过的

**Comment by ustbhuangyi** [comment]
https://m.taobao.com
他应该是根据js动态计算插入的

**Comment by anUglyDog** [comment]
是的,我现在也是模仿他的这个.你说的lib-flexible不也是一样的吗?
