### ISSUE TITLE
新需求：添加重载的方法

### ISSUE THREAD

**Issue by CommanderXL** [ustbhuangyi/picker#9]
业务场景：

在一些页面当中，可能存在多个需要用到`picker`组件的地方。如果每次都`new`一个新的`picker`，会在`DOM`当中新插入一个`picker`。可以只使用一个`picker`来满足多个需要选择的业务场景

可添加2个方法：
- changeTitle
- reConstruct

`changeTitle`用以改变`title`的显示，`reConstruct`区别于`refill`方法，可以提供3列选项的替换.

**Comment by ustbhuangyi** [comment]
从组件化的角度来看，picker 是一个单独的组件，在每一个用到的地方实例化一个 picker 无可厚非。picker 如果做成单例模式，会引发很多问题，因为我们是通过 picker 派发出来的事件和外部通讯的，如果多处共用一个 picker，那么事件通讯这块就乱了~
从性能的角度来看，虽然会多个 picker 会在 dom 上插入多次，但是没有使用的 picker 的 display 是 'none'，并不会渲染，所以也是没问题的~
